apiVersion: v1
kind: Template
metadata:
  name: rporresm-test-diag-container
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: rporresm-test-diag-container
    name: rporresm-test-diag-container
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: rporresm-test-diag-container
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    template:
      metadata:
        labels:
          app: rporresm-test-diag-container
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          name: rporresm-test-diag-container
          resources:
            limits:
              cpu: ${{CPU_LIMIT}}
              memory: ${{MEMORY_LIMIT}}
            requests:
              cpu: ${{CPU_REQUEST}}
              memory: ${{MEMORY_REQUEST}}
parameters:
- name: IMAGE
  value: quay.io/app-sre/rporresm-test-diag-container
- name: IMAGE_TAG
  value: latest
- name: POSTGRES_DB_SECRET_NAME
  value: ""
- name: PGCONNECT_TIMEOUT
  value: "30"
  required: true
- name: PGSSLMODE
  value: "require"
  required: true
- name: CPU_REQUEST
  value: "100m"
  required: true
- name: MEMORY_REQUEST
  value: "128Mi"
  required: true
- name: MEMORY_LIMIT
  value: "1Gi"
  required: true
- name: CPU_LIMIT
  value: "1000m"
  required: true
