apiVersion: v1
kind: Template
metadata:
  name: pipelines-test-container
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: ${NAME}
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    template:
      metadata:
        labels:
          app: ${NAME}
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          name: pipelines-test-container
          resources:
            limits:
              cpu: ${{CPU_LIMIT}}
              memory: ${{MEMORY_LIMIT}}
            requests:
              cpu: ${{CPU_REQUEST}}
              memory: ${{MEMORY_REQUEST}}
parameters:
- name: IMAGE
  value: quay.io/app-sre/pipelines-test-container
- name: IMAGE_TAG
  value: latest
- name: NAME
  value: pipelines-test-container
- name: CPU_REQUEST
  value: "10m"
  required: true
- name: MEMORY_REQUEST
  value: "1Mi"
  required: true
- name: MEMORY_LIMIT
  value: "32Mi"
  required: true
- name: CPU_LIMIT
  value: "100m"
  required: true
